# NumPy 

pandas >>> dataframe
numpy >>> n-dimension array

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
n1 = np.array(l)

In [4]:
type(n1)

numpy.ndarray

In [5]:
n1

array([1, 2, 3, 4, 5])

In [6]:
l

[1, 2, 3, 4, 5]

In [7]:
#arange() -> create an array of given range

In [8]:
n2 = np.arange(1,101)

In [9]:
n2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
#numpy array of one(1)

In [11]:
n3 = np.ones(10)

In [12]:
n3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
#numpy array of zeros(0)

In [14]:
n4 = np.zeros(5)

In [15]:
n4

array([0., 0., 0., 0., 0.])

In [16]:
#random numbers in a given range

In [17]:
n5 = np.random.randint(1,100,10)

In [18]:
n5

array([24, 41, 71, 45, 81, 57, 10, 21, 14, 62])

In [19]:
#random number in the range(0-1) -> 1-D array

In [20]:
n6 = np.random.rand(2)

In [21]:
n6

array([0.50978118, 0.15342797])

In [22]:
np.random.rand(4,5) #rand() for n-D array

array([[0.7016502 , 0.52972508, 0.14883295, 0.35761872, 0.61787076],
       [0.57649871, 0.85271573, 0.48793636, 0.5817621 , 0.11509715],
       [0.07932136, 0.86036398, 0.59725097, 0.36295937, 0.04982375],
       [0.04832802, 0.76048617, 0.26914874, 0.37479688, 0.46676905]])

In [23]:
#linspace -> in a given range with equidistance between the numbers

In [24]:
n7 = np.linspace(1, 100, 10) #end index included(exception in python)

In [25]:
n7

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [26]:
#numpy to create identity matrix

In [27]:
n8 = np.eye(4)

In [28]:
n8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#numpy array in the range 1-25

In [30]:
n_1_25 = np.arange(1,26)

In [31]:
n_1_25

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [32]:
n_1_25.shape

(25,)

In [33]:
new_narr = n_1_25.reshape(5,5)

In [34]:
new_narr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
new_narr.shape

(5, 5)

In [36]:
new_narr2 = n_1_25.reshape(1,25)

In [37]:
new_narr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [38]:
new_narr2.shape #note the difference between 'n_1_25' and 'new_narr2' shape

(1, 25)

In [39]:
new_narr3 = n_1_25.reshape(25,1)

In [40]:
new_narr3

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [41]:
new_narr3.shape

(25, 1)

In [42]:
#numpy array of numbers 1 to 10

In [43]:
n1_10 = np.arange(1,11)

In [44]:
n1_10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
#fetch first 3 numbers from numpy array

In [46]:
n1_10[0:3]

array([1, 2, 3])

In [47]:
n1_10[-3:]

array([ 8,  9, 10])

In [48]:
#BROADCASTING

In [49]:
n1_10[0:4] = 100

In [50]:
n1_10

array([100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
p = n1_10 #p pointing to the same memory location as n1_10, thus changes made in p reflected in n1_10

In [52]:
p[0:4] = 200

In [53]:
p

array([200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [54]:
n1_10

array([200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [55]:
q = p.copy() #create copy of p in new memory location, thus changes made in q can't be reflected in p

In [56]:
q[0:4] = 500

In [57]:
q

array([500, 500, 500, 500,   5,   6,   7,   8,   9,  10])

In [58]:
p

array([200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [59]:
n1_10

array([200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [60]:
#2D numpy array in the range(1,9) of dimension 3*3

In [61]:
arr_2d = np.arange(1,10).reshape(3,3)

In [62]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr_2d[0]

array([1, 2, 3])

In [64]:
arr_2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
#fancy indexing

In [66]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [67]:
arr_2d[0:3,0:2] #OR arr_2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [68]:
n = np.arange(1,11)

In [69]:
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
#ARITHMATIC Feature of numpy array

In [71]:
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
n + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
n - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [74]:
n * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
n / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [76]:
n + n

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [77]:
#Random numpy array of dimesion 5*4

In [78]:
nd_arr = np.random.rand(5,4)

In [79]:
nd_arr

array([[0.26786701, 0.26146856, 0.04602356, 0.13705208],
       [0.67249162, 0.42167337, 0.00819845, 0.23192917],
       [0.61331192, 0.16976647, 0.96249092, 0.60031971],
       [0.4388136 , 0.80804862, 0.96359411, 0.94332398],
       [0.99405177, 0.71532003, 0.35002811, 0.96392256]])