In [1]:
import numpy as np

In [2]:
#Filter elements in numpy array

In [3]:
narr = np.arange(1,21)

In [4]:
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
bool_narr = narr < 10

In [6]:
narr[bool_narr]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
narr[narr < 5]

array([1, 2, 3, 4])

In [8]:
#Dataframe from numpy array

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(data = np.random.rand(5,4),
                  index = 'A B C D E'.split(),
                 columns = 'W X Y Z'.split())

In [11]:
df

W         X         Y         Z
A  0.842041  0.155473  0.034681  0.841052
B  0.581742  0.192610  0.070015  0.250116
C  0.105821  0.203430  0.892905  0.316684
D  0.616267  0.441446  0.236031  0.046256
E  0.727507  0.042748  0.156745  0.720598

In [12]:
#Filtering elements in pandas dataframe

In [13]:
df < 0.5

W     X      Y      Z
A  False  True   True  False
B  False  True   True   True
C   True  True  False   True
D  False  True   True   True
E  False  True   True  False

In [14]:
df[df<0.5]

W         X         Y         Z
A       NaN  0.155473  0.034681       NaN
B       NaN  0.192610  0.070015  0.250116
C  0.105821  0.203430       NaN  0.316684
D       NaN  0.441446  0.236031  0.046256
E       NaN  0.042748  0.156745       NaN

In [15]:
df['W']<0.5

A    False
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [16]:
df[df['W']<0.5]

W        X         Y         Z
C  0.105821  0.20343  0.892905  0.316684

In [17]:
df[df['W']<0.5]['X']

C    0.20343
Name: X, dtype: float64